name: Avereon Website CI

on: [push]

env:
  AVN_PRODUCT: "zevra"
  # The default release, should be overridden in config.sh
  AVN_RELEASE: "latest"
  # The default platform, should be overridden in the platform binaries jobs below
  #AVN_PLATFORM: "linux"

  AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
  AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
  AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
  AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "11"
  MAVEN_PARMS: "-B -U -V --settings ../.github/settings.xml --file pom.xml"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v1

      - name: Fetch CI/CD resources
        uses: actions/checkout@v2
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      # Required to render the product icon
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: NPM Repository Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Client
        run: |
          cd client
          npm install-clean
          npm run-script build
          cd build
          zip -r ../client.zip *

      - name: Build Server
        run: |
          cd server
          mvn ${{env.MAVEN_PARMS}} package

      - name: Copy Client ZIP
        run: scp -B client/client.zip travis@avereon.com:/opt/avn/store/latest/www.avereon.com/client.zip

      - name: Copy Server JAR
        run: scp -B server/target/avereon.jar travis@avereon.com:/opt/avn/store/latest/www.avereon.com/server.jar

      - name: Copy Provider Icon
        run: scp -B server/target/main/images/avereon.png travis@avereon.com:/opt/avn/store/stable/avereon/provider.png

      - name: Update the Website
        run: ssh travis@avereon.com /home/ecco/bin/update-avereon-website
