name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      env:
        AVN_MAVEN_USERNAME: ${{ secrets.AVN_MAVEN_USERNAME }}
        DISPLAY: ":99"
      run: |
        echo "Maven user: ${AVN_MAVEN_USERNAME}"
#        Xvfb ${DISPLAY} -screen 0 1920x1080x24 -nolisten unix &
#        mvn package -B -U -V --settings .github/settings.xml --file pom.xml
