name: Avereon Server CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: .github/build.sh
    - name: Deploy
      env:
        TRAVIS_SSH_KEY: ${{ secrets.TRAVIS_SSH_KEY }}
        TRAVIS_SSH_PUB: ${{ secrets.TRAVIS_SSH_PUB }}
      run: .github/deploy.sh
